### ISSUE TITLE
Suggestions for Project Management

### ISSUE THREAD

**Issue by ovflowd** [chrismpettyjohn/Heroic#4]
Hey, I would **highly** recommend you using the GtiHub Issues and the Project Kanban boards to track your progress and current bugs, problems, suggestions and et cetera. It would be good for new contributor and users know what you're struggling, doing, and going to achieve. Also would be good for developers like me in order to try giving suggestions and helping you in your current bugs.

👍 ✌️

**Comment by chrismpettyjohn** [comment]
Due to the lack of community involvement and other developer involvement; outside of yourself - I believe issue tracking would not only be a waste of time at this current moment, but it would not be too helpful.  I currently use Discord for community-involvement.  Thanks for the suggestion

**Comment by chrismpettyjohn** [comment]
I have actually taken your idea into consideration and am going to redo how I manage this project.  Projects have been added and support for Heroic 2 is ideal.  
https://github.com/chrismpettyjohn/Heroic/projects/1

The Discord is located at https://discord.gg/y6szGk5

**Comment by ovflowd** [comment]
Thanks @chrismpettyjohn, If you need anything, count me in 😄
