### ISSUE TITLE
cms is broken

### ISSUE THREAD

**Issue by Firjen** [chrismpettyjohn/Heroic#58]
When I put Heroic on ISIS or XAMPP it doesn't do anything?????????????????????????????????
Your CMS is real shit and sucks dick, I'm going to use brainCMs.

- Hackerman

**Comment by chrismpettyjohn** [comment]
I sprinkled some American on it so it should work now
![image](https://user-images.githubusercontent.com/2059790/46891601-00161780-ce30-11e8-8f45-0f142e47702a.png)

**Comment by Firjen** [comment]
Now I need to insert a micro transaction.
