### ISSUE TITLE
Missing SQL tables

### ISSUE THREAD

**Issue by thomasvvugt** [chrismpettyjohn/Heroic#59]
On a fresh installation, some tables are missing like the users table. Please provide a clean database SQL file.

**Comment by chrismpettyjohn** [comment]
Those tables will be apart of the emulator SQL.  Heroic uses Arcturus which can be located here (http://arcturus.pw/mirrors/) - The license prevents me from rehosting myself.

**Comment by thomasvvugt** [comment]
I am still missing the heroic.sql file, as stated in the README. Is this just me?

**Comment by chrismpettyjohn** [comment]
> I am still missing the heroic.sql file, as stated in the README. Is this just me?

It was removed by accident during the big update.  Will be added back in a commit coming soon

**Comment by rsmsha** [comment]
If you need an alternative right now, here is clean SQL that was a result of importing Arcturus SQL and Heroic SQL, but I wouldn't recommend it for anything other than testing. Id wait for the official SQL to be up again and import that with the Arcturus SQL.
https://gist.github.com/rsmsha/6dba982b20fd982634c55d0cb3bf39cc

**Comment by chrismpettyjohn** [comment]
The official SQL is back again.
https://github.com/chrismpettyjohn/Heroic/commit/15142e519b270c0e0961ae0ca87d90f4859236cf
